// webui/scripts/gen-i18n.mjs
// Tek kaynak: ports/RGSX/languages/{tr,en,fr,de,es,it,pt}.json
// WebUI'nin kullandığı anahtarları (tt('x') / loc('x') çağrıları) tarar ve
// webui/src/i18n.strings.js dosyasını üretir. i18n.js bu dosyayı import eder.
// Çalıştır: npm run gen:i18n   (build öncesi otomatik çağrılır)

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_LANGS = 'ports/RGSX/languages';
const LANGS = ['tr', 'en', 'fr', 'de', 'es', 'it', 'pt'];
const FALLBACK = 'en';

const langDir = resolve(__dirname, '..', '..', REPO_LANGS);
const outFile = resolve(__dirname, '..', 'src', 'i18n.strings.js');
const srcDir = resolve(__dirname, '..', 'src');

// 1) Python JSON'larını oku
const data = {};
for (const l of LANGS) {
  const p = resolve(langDir, `${l}.json`);
  if (!existsSync(p)) {
    console.error(`[gen-i18n] EKSİK: ${p}`);
    process.exit(1);
  }
  data[l] = JSON.parse(readFileSync(p, 'utf8'));
}

// 2) WebUI kaynakkodunda kullanılan anahtarları tara (tt('x') / loc('x'))
function scanDir(dir, keys) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === 'node_modules' || e.name === 'dist') continue;
      scanDir(full, keys);
    } else if (/\.(vue|js|mjs|ts)$/.test(e.name)) {
      if (e.name === 'i18n.strings.js') continue; // kendini taramayacağız
      const txt = readFileSync(full, 'utf8');
      const re = /(?<![A-Za-z0-9_])(?:tt|loc|t)\(\s*['"]([A-Za-z0-9_]+)['"]\s*\)/g;
      let m;
      while ((m = re.exec(txt))) keys.add(m[1]);
    }
  }
}
const usedKeys = new Set();
scanDir(srcDir, usedKeys);
console.log(`[gen-i18n] kullanılan anahtar: ${usedKeys.size}`);

// 3) STRINGS nesnesini üret (her dil için kullanılan anahtarlar; eksikse fallback)
const STRINGS = {};
for (const l of LANGS) {
  STRINGS[l] = {};
  for (const k of usedKeys) {
    let v = data[l][k];
    if (v === undefined) v = data[FALLBACK][k];
    if (v === undefined) v = data.tr[k];
    if (v !== undefined) STRINGS[l][k] = v;
    else console.warn(`[gen-i18n] anahtar '${k}' hiçbir dilde yok`);
  }
}

// 4) Dosyaya yaz
const header =
  '// AUTO-GENERATED by webui/scripts/gen-i18n.mjs — ELLE DÜZENLEMEYİN.\n' +
  '// Tek kaynak: ports/RGSX/languages/*.json\n' +
  '// Yeniden üret: npm run gen:i18n\n';
const body = JSON.stringify(STRINGS, null, 2);
writeFileSync(outFile, header + `export const STRINGS = ${body};\n`, 'utf8');
console.log(`[gen-i18n] yazıldı: ${outFile}`);
